### ISSUE TITLE
Feature: DropCreateDatabaseAlways

### ISSUE THREAD

**Issue by code1line** [msallin/SQLiteCodeFirst#10]
I would like to include the ability to delete the database each time. Certainly a good feature during development!

**Comment by msallin** [comment]
I'll rename the `SqliteContextInitializer` to `SqliteInitializerBase` and make this class abstract.

Then I'm going to create two new classes `SqliteDropCreateDatabaseAlways` and `SqliteCreateDatabaseIfNotExists` which are both `public`.

What do you think?

**Comment by code1line** [comment]
I have successfully tested with an optional parameter, but your suggestion is certainly the better and cleaner approach.

**Comment by msallin** [comment]
I pushed the edited code. Feel free to try/test it.

**Comment by code1line** [comment]
Works!
