### ISSUE TITLE
support for GUID type primary key ID column with auto generated value

### ISSUE THREAD

**Issue by koo9** [msallin/SQLiteCodeFirst#101]
when having this entity type configuration settting for a guid type Id,

this.Property(t => t.Id)
				.HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);

the database does not have a default value for the Id primary key column. is it a known issue?

thx

**Comment by msallin** [comment]
Does SQLite support autogenerate Guids as primary key?

**Comment by jonkeda** [comment]
No, not according to Google. Only examples are fake Guids.

**Comment by msallin** [comment]
The generation of the identity column belongs to the mechanism of SQLite.
As SQLite does not support the autogeneration of GUIDs as primary key, I can also not implement this feature for this library. Consider to use e.g. triggers, which are supported.
