### ISSUE TITLE
Update table with database sqlite exists

### ISSUE THREAD

**Issue by tuanth89** [msallin/SQLiteCodeFirst#102]
Hi, firstly. Thank for SqliteCodeFirst project!
How to update table change (ex: add field) with database exists ?
I just found 3 class:
- SqliteCreateDatabaseIfNotExists.cs
- SqliteDropCreateDatabaseAlways.cs
- SqliteDropCreateDatabaseWhenModelChanges.cs

Which way UpdateDatabaseWhenModelChange ?
I don't want drop db because relate to important data.

Thanks

**Comment by msallin** [comment]
Hi

Migrations are not supported (https://github.com/msallin/SQLiteCodeFirst/issues/4).
Its easy to create a migration like feature by yourself. This is what I did once for a project.
You can create your own initializer and use this library to generate the database if it not exists.
