### ISSUE TITLE
Table creation issue with SQL reserved word property names

### ISSUE THREAD

**Issue by jjbutera** [msallin/SQLiteCodeFirst#107]
I'm sure it's just a bracketing issue on the SQL create statements. My entity has a property named Order which fails to generated the database file (syntax error). When renamed to Orderx, it works fine.

After some trial and error, I've determined the issue occurs when a reserved word property is part of an index. The DB creation works fine if I comment out the index annotation above Order:

`

		[Index("IX_MacroCommandDuplicate", Order = 1, IsUnique = true)]
		public int MacroStepId { get; set; }

		[Index("IX_MacroCommandDuplicate", Order = 2, IsUnique = true)]
		public int Order { get; set; }
`

Possible fix:
CreateIndexStatement.cs

`
IEnumerable<string> orderedColumnNames = Columns.OrderBy(c => c.Order).Select(c => $"[{c.Name}]");
`

**Comment by msallin** [comment]
Thank you for creating the issue, it is fixed with the version 1.5.
To support this project you can
- star the repository;
- report bugs/request features by creating new issues;
- write code and create PRs;
- donate.

https://github.com/msallin/SQLiteCodeFirst/tree/v1.5.0.21#support-the-project-
