### ISSUE TITLE
Add Initializer for both "IfNotExists" and "ModelChanges"

### ISSUE THREAD

**Issue by SalehBagheri** [msallin/SQLiteCodeFirst#108]
My program uses SqliteCodeFirst.
In first run, my program should use "DatabaseIfNotExists" initializer, and after update to new version, my program should use "WhenModelChanges" initializer.

How can I handle this problem?

**Comment by CADbloke** [comment]
## See also #4 
This is probably more a StackOverflow question but here are some leads...

https://www.google.com/search?q=entity+framework+6+custom+initializer
https://www.google.com/search?q=entity+framework+6+custom+initializer+migrate

https://www.codeguru.com/csharp/article.php/c19999/Understanding-Database-Initializers-in-Entity-Framework-Code-First.htm  <== has some sample code

https://www.tektutorialshub.com/custom-database-initializer-in-entity-framework/ <== don't forget to run an ad-blocker but seems to have a half-decent beginner's overview
