### ISSUE TITLE
SqliteDropCreateDatabaseWhenModelChanges not work

### ISSUE THREAD

**Issue by ghost1372** [msallin/SQLiteCodeFirst#112]
hi i want use SqliteDropCreateDatabaseWhenModelChanges this is my codes:
app.Config:
```XML
<connectionStrings>
    <add name="default" connectionString="data source=app.db;" providerName="System.Data.SQLite" />
  </connectionStrings>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v13.0" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SQLite" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
      <remove invariant="System.Data.SQLite" />
      <add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" />
    </DbProviderFactories>
  </system.data>
```
and this is my dbContext class:
```C#
public class TestDbContext : DbContext
    {
        public virtual DbSet<User> Users { get; set; }

        public TestDbContext()
            : base("default")
        { }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            var sqliteConnectionInitializer = new SqliteCreateDatabaseIfNotExists<TestDbContext>(modelBuilder);
            Database.SetInitializer(sqliteConnectionInitializer);

        }
    }
```
and last step Main.cs:
```C#
 var db = new TestDbContext();
            var users = db.Users.ToList();
```
with this code i can create database, but when i use SqliteDropCreateDatabaseWhenModelChanges  like this i get error:
```C#
public class TestDbContext : DbContext
    {
        public virtual DbSet<User> Users { get; set; }

        public TestDbContext()
            : base("default")
        { }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            var sqliteConnectionInitializer = new MyDbContextInitializer(modelBuilder);

            Database.SetInitializer(sqliteConnectionInitializer);

        }
        public class MyDbContextInitializer : SqliteDropCreateDatabaseWhenModelChanges<TestDbContext>
        {
            public MyDbContextInitializer(DbModelBuilder modelBuilder)
                : base(modelBuilder) { }

            protected override void Seed(TestDbContext context)
            {
                context.Users.Add(new User
                {
                    Name = "Richard Niemand",
                    Created = DateTime.Now
                });

                base.Seed(context);
            }
        }

    }
```

Error:
```
System.MissingMethodException: 'Method not found: 'Void System.Data.Entity.DbModelBuilder.RegisterEntityType(System.Type)'.'
```

**Comment by msallin** [comment]
You have to update to EF v6.2 you can do this manually or update to the newest SQLite.CodeFirst Package.

**Comment by ghost1372** [comment]
@msallin  tnx i tested everything is ok but when my model changed i get this error is it normal? or its a new bug?
(i just created simple database in this case app work fine, but when i change some columns and run again i get this error)

System.Data.DataException
  HResult=0x80131501
  Message=An exception occurred while initializing the database. See the InnerException for details.
  Source=EntityFramework
  StackTrace:
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at WindowsFormsApp10.Form1.Form1_Load(Object sender, EventArgs e) in c:\users\mahdi\source\repos\WindowsFormsApp10\WindowsFormsApp10\Form1.cs:line 22
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Inner Exception 1:
DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.

**Comment by Jiraiyah** [comment]
I have EF 6.2 but the seed method on SqliteDropCreateDatabaseWhenModelChanges still is not working, have the latest version of your nuget too.

`
public class BitmexDBContext : DbContext
    {
        public DbSet<NetworkSettings> NetworkSetting { get; set; }
        public DbSet<InterfaceSettings> InterfaceSetting { get; set; }

        /*public BitmexDBContext() : base(Program.DBConnectionStringName) { } //"BitmexDBCS") {}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            
        }*/
        public BitmexDBContext() : base("BitmexBotDB")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            var sqliteConnectionInitializer =
                new SqliteDropCreateDatabaseWhenModelChanges<BitmexDBContext>(modelBuilder);
            System.Data.Entity.Database.SetInitializer(sqliteConnectionInitializer);
        }

        public class BitmexDBContextInitializer : SqliteDropCreateDatabaseWhenModelChanges<BitmexDBContext>
        {
            public BitmexDBContextInitializer(DbModelBuilder modelBuilder)
                : base(modelBuilder)
            {
            }

            protected override void Seed(BitmexDBContext context)
            {
                context.Set<NetworkSettings>().Add(new NetworkSettings
                {
                    MainDomain = @"https://www.bitmex.com",
                    MainAPI = "",
                    MainSecret = "",
                    TestDomain = @"https://testnet.bitmex.com",
                    TestAPI = "",
                    TestSecret = "",
                    MainSocketURL = "wss://www.bitmex.com/realtime",
                    TestSocketURL = "wss://testnet.bitmex.com/realtime",
                    License = "NONE"
                });
            }
        }
    }
`

**Comment by msallin** [comment]
Please upload a full build and executable repro solution somewhere and post the link.
Then I'll have a look at it.

**Comment by Jiraiyah** [comment]
> Please upload a full build and executable repro solution somewhere and post the link.
> Then I'll have a look at it.

in my case, i can't, don't have permission from team and also, there are 3rd party components that we use and their legal notes don't let us. but all the data related to the db, is in my post. right now, i do a trick and at the start of software i check if the dbset is null, then i generate the seed data and save the db, it's doing the job, but it's not a real seeding method.
