### ISSUE TITLE
not work on WPF

### ISSUE THREAD

**Issue by ghost1372** [msallin/SQLiteCodeFirst#113]
i cant use it on wpf
  there is no method : 
Database.SetInitializer(sqliteConnectionInitializer);

**Comment by msallin** [comment]
Please provide more information. I'll not be able to reproduce it this way.
The simplest thing would be to upload your code.

**Comment by ghost1372** [comment]
sorry its my mistake, I had a folder called Database, and my classes were there so when i wrote  Database.SetInitializer(sqliteConnectionInitializer);
i get error tnx for your response 👍
