### ISSUE TITLE
Cryptography Class “SHA512Managed” is Not FIPS Compliance

### ISSUE THREAD

**Issue by satheeskumarmanickam** [msallin/SQLiteCodeFirst#118]
Hi Sallin,

During testing we observed that “SQLite.CodeFirst Version 1.5.0.21” which is referred in our project is not FIPS Compliance (which is default security settings as part of Windows 2008 Server). 

Recommending the following changes to make it FIPS Compliance,
1.	“HashCreator.cs” file uses the Cryptography class “SHA512Managed” which is not FIPS Compliance.
2.	Instead we can use “SHA512Cng” to make FIPS Compliance.

I request you to address this issue in the next release.

Regards,
Satheeskumar.M

**Comment by msallin** [comment]
Why do you think one benefits of using a secure hash function for this purpose?

**Comment by msallin** [comment]
Closed due to inactivity.
