### ISSUE TITLE
Project does not compile

### ISSUE THREAD

**Issue by HarelM** [msallin/SQLiteCodeFirst#12]
Hi,

When getting latest version the code does not compile due to what I believe was a rename of `SqliteDropCreateDatabaseAlwaysBaseInitializer` to `SqliteDropCreateDatabaseAlways`.

**Comment by msallin** [comment]
Hi

Its fixed with the following commit https://github.com/msallin/SQLiteCodeFirst/commit/5fda7bdb4ec33a5360b9c42d4eabc2de53ac4c13
