### ISSUE TITLE
InvalidOperationException on README sample

### ISSUE THREAD

**Issue by astorDev** [msallin/SQLiteCodeFirst#120]
try to used following context, almost entirely copied from README

        public class CookbookDbContext : DbContext
        {
		public DbSet<DishData> Dishes { get; set; }

		public CookbookDbContext(DbConnection existingConnection) : base(existingConnection, true)
		{
		}

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			var model = modelBuilder.Build(Database.Connection);
			IDatabaseCreator sqliteDatabaseCreator = new SqliteDatabaseCreator();
			sqliteDatabaseCreator.Create(this.Database, model);
		}
        }

in the test method

                    using (var context = new CookbookDbContext(new SQLiteConnection("DataSource=:memory:")))
			{
				context.Dishes.Add(new DishData() { Name = "Spaghetti" });
				context.SaveChanges();

				Assert.AreEqual(1, context.Dishes.Count());
				Assert.AreEqual("Spaghetti", context.Dishes.First().Name);
			}

caused following exception:

> System.InvalidOperationException: The context cannot be used while the model is being created. This exception may be thrown if the context is used inside the OnModelCreating method or if the same context instance is accessed by multiple threads concurrently. Note that instance members of DbContext and related classes are not guaranteed to be thread safe.

**Comment by msallin** [comment]
Can you please upload the whole project?

**Comment by msallin** [comment]
Same as https://github.com/msallin/SQLiteCodeFirst/issues/121?

**Comment by msallin** [comment]
If you use the in memory db, you have to call `Connection.Open();` before accessing the context.
See e.g. in InMemoryDbCreationTest
