### ISSUE TITLE
windows form startup  sample 

### ISSUE THREAD

**Issue by msh2050** [msallin/SQLiteCodeFirst#124]
Please is there easy winform sample

**Comment by ghost1372** [comment]
hey check my repo
https://github.com/ghost1372/MoalemYar

**Comment by msallin** [comment]
Look at the sample application in the repository: https://github.com/msallin/SQLiteCodeFirst/tree/master/SQLite.CodeFirst.Console
It is a console application but there is nothing specific, you can use the same code for your WinForm app.
