### ISSUE TITLE
update database or import data to new version

### ISSUE THREAD

**Issue by ghost1372** [msallin/SQLiteCodeFirst#125]
hi i have a database with data i want when i updated my model and database recreated my data transfer to new database, so how i can do this?

**Comment by msallin** [comment]
Hello

It does not sound like you can achive your goal with this library.
I guess what you are looking for is a migration feature (apply schema migrations to your existing database). This feature is not supported (https://github.com/msallin/SQLiteCodeFirst/issues/4). But you can easy write a own migrations framework and use another initialize which does not drop your database on model change.

Greetings

**Comment by digocesar** [comment]
Hi @ghost1372 .
I have been working with this SQLiteCodeFirst project and a Migration feature. Take a look at https://github.com/digocesar/SQLiteCodeFirst.
It is the @msallin project with @zanyants migration code. But @zanyants never had updated his fork project.

Migrations with Sqlite have some limitations due to Sqlite ALTER command limitations.

**Comment by ghost1372** [comment]
thank you @digocesar  Your work is great, can i use it from nuget?

**Comment by digocesar** [comment]
My project isn't in nuget.
It is just the @msallin project with one more file: [SqliteMigrationSqlGenerator.cs](https://github.com/digocesar/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/Public/SqliteMigrationSqlGenerator.cs)
I think that should be better include this file at @msallin project. But I don't know why it never happened.

**Comment by ghost1372** [comment]
ok, good question
 @msallin  why you dont  include this file? Is there a problem with the file or has any other reason?
Anyway, thank you all for your work

**Comment by ghost1372** [comment]
hey @digocesar 
i cant use your migration, Some codes are not detected and they make errors, can you make a simple example project?
![untitled](https://user-images.githubusercontent.com/9213496/39907663-5ef2528c-54ff-11e8-9d8f-13426ec0e072.png)

**Comment by msallin** [comment]
@ghost1372 @digocesar it never happend because I never get a PR ;) Feel free to create one.

**Comment by digocesar** [comment]
Hi @ghost1372.

Change "DatabaseManager.ProviderName" by "System.Data.SQLite". DatabaseManager was a class in my project. I fixed my [example](https://github.com/digocesar/SQLiteCodeFirst#sqlitemigrationsqlgenerator-sample).

The "Migrations.Configuration" are Folder and File created by "enable-migrations" command at Package Manager Console. But your "Configuration" class looks like a inner class. Did you created it manually? Take a look at [this post](https://docs.microsoft.com/en-us/aspnet/mvc/overview/getting-started/getting-started-with-ef-using-mvc/migrations-and-deployment-with-the-entity-framework-in-an-asp-net-mvc-application) to create Migrations classes.

I'm working in a Console Demo application to publish with the project. ;)

**Comment by ghost1372** [comment]
@digocesar  tnx now i have little problem, my database My database is created but there is no table in it

**Comment by ghost1372** [comment]
@digocesar  tnx now i have little problem, my database My database is created but there is no table in it

**Comment by ghost1372** [comment]
@digocesar  tnx my problem fixed

> Migrations with Sqlite have some limitations due to Sqlite ALTER command limitations.

is it possible to fix this limitations?

**Comment by digocesar** [comment]
When renaming a column, for example, EF creates the code
`Rename("dto.table_name", "old_name", "new_name");`
But if you try to run it will get an Exception saying that Sqlite can't rename columns.
The workaround we do is:
- disable Sqlite foreingkey validation
- rename old table to one temporary name
- create new table with the new column
- add a SQL to copy data from old table to the new table
- drops old table
- enable Sqlite foreingkey validation if you are using it

This is an example of my application changing column name "CurrentValue" to "DefaultValue":
![image](https://user-images.githubusercontent.com/17618149/39933897-923aa55c-551a-11e8-919a-1fef4c1e7cb2.png)

**Comment by ghost1372** [comment]
can you share GetEnableForeingKeyStatement() ?
i cant access this func

**Comment by digocesar** [comment]
Sorry for late response. Just now I see your request.
GetEnableForeingKeyStatement() is an internal function that looks at current ConnectionString if the option "Foreign Keys" was enabled or not.
I will post my code but it possible will not fit to you case.
```C#
private static string GetEnableForeingKeyStatement()
{
    using (var databaseManager = new DatabaseManager())
    {
        var sEnableForeignKeys = "false";

        var connectionString = new DbConnectionStringBuilder
        {
            ConnectionString = databaseManager.GetConnectionString()
        };

        if (connectionString.ContainsKey("Foreign Keys"))
            sEnableForeignKeys = connectionString["Foreign Keys"].ToString();

        return string.Format("PRAGMA foreign_keys = {0}", sEnableForeignKeys);
    }
}
```

**Comment by digocesar** [comment]
@msallin I'm trying to include in Sqlite.CodeFirst the project of Migrations. But I had a problem that people sad that was a error in Sqlite 1.0.106 and EF 6.2.
When I try to update Sqlite to 1.0.108 in the Sqlite.CodeFirst project I get a error run Console or tests.
`Unable to determine the provider name for provider factory of type 'System.Data.SQLite.SQLiteFactory'. Make sure that the ADO.NET provider is installed or registered in the application config.`
Could you update you project to Sqlite 1.0.108 and try to figured out what is happening?

**Comment by digocesar** [comment]
@msallin Forget it. Nuget has changed the App.config when upgrading Sqlite version. I fixed it.

**Comment by digocesar** [comment]
Hi @msallin.
Just now I had time to finish an example project with [SqliteCodeFirst and Migrations](https://github.com/digocesar/SQLiteCodeFirst/).
But I had problem with EF 6.2.0. [This error](https://stackoverflow.com/questions/47329496/updating-to-ef-6-2-0-from-ef-6-1-3-causes-cannot-access-a-disposed-object-error) happens when I need to run Migrations commands at Package Manager Console. This problem was introduced in EF 6.2.0 and is [fixed](https://github.com/aspnet/EntityFramework6/issues/398) to EF 6.3.
I suppose that downgrade SQLiteCodeFirst to EF 6.1.3 is not possible because of database at Memory.
What do you think? Is possible to reintegrate these changes to you project? Keep separated until EF 6.3 is released? Or do you have some suggestion of workaround to use Migrations with EF 6.2.0?

**Comment by msallin** [comment]
Can you create a PR and open the discussion there?
As this ticket is about a different topic I will close it.
Thx
