### ISSUE TITLE
Problem with DateTime columns

### ISSUE THREAD

**Issue by spudcz** [msallin/SQLiteCodeFirst#130]
When you save datetime value in UTC to SQLite and retrive it as part of typed model class it returns correctly as UTC datetime value. When you retrieve it as part of anonymous class it push datetime value to localtime and returns Kind as unspecified.

    public class SampleTable
    {
        [Autoincrement, Key]
        public int Id { get; set; }
        public DateTime Created { get; set; }
    }

    public class SampleContext : DbContext
    {
        public SampleContext() : base("name=sampleConnection")  { }

        protected override void OnModelCreating(DbModelBuilder modelBuilder) {
            Database.SetInitializer(new SqliteCreateDatabaseIfNotExists<SampleContext>(modelBuilder));
        }

        public DbSet<SampleTable> SampleTables { get; set; }
    }

    using (var ctx = new SampleContext())
    {
        // saved to DB as UTC time
        ctx.SampleTables.Add(new SampleTable {Created = DateTime.UtcNow});
        ctx.SaveChanges();

        // from DB loaded as UTC time - correct
        SampleTable itemTyped = ctx.SampleTables
            .OrderByDescending(x => x.Id)
            .First();
        Console.WriteLine($"DateTime loaded: {itemTyped.Created}, kind: {itemTyped.Created.Kind}, in local time: {itemTyped.Created.ToLocalTime()}");

        // from DB loaded as localtime, kind set to unspecified - wrong
        var itemUntyped = ctx.SampleTables
            .OrderByDescending(x => x.Id)
            .Select(x => new {
                x.Id,
                x.Created
            })
            .First();
        Console.WriteLine($"DateTime loaded: {itemUntyped.Created}, kind: {itemUntyped.Created.Kind}, in local time: {itemUntyped.Created.ToLocalTime()}");
    }

**Comment by msallin** [comment]
This issue is EF releated and there is no connection to the SQLite.CodeFirst library.
