### ISSUE TITLE
Thank-you

### ISSUE THREAD

**Issue by ToddThomson** [msallin/SQLiteCodeFirst#132]
Just a quick thank-you from [Entities.Sqlite](https://github.com/achilles-software/entities.sqlite). We utilized a few of your ideas and used some modified source from your project. Your project license will be included as required.

BTW: Your license file does not contain a year and copyright owner. I have used 2018 and "Mark Sallin". Let me know if that is OK.

**Comment by msallin** [comment]
Hi Todd 

Glad to see, that you can use a part of this project!
Thank you for the hint. I adjusted the license file.
My first name is written with "c" instead of "k".
Would be great if you can correct this! :)

Greetings Marc
