### ISSUE TITLE
Double foreign Keys

### ISSUE THREAD

**Issue by WonderGnagno** [msallin/SQLiteCodeFirst#135]
Hi,
I've a Parent table with a Child Table. The child table has two fields that refers to Id of his Parent.
My aim is to add two foreign key delete on cascade on both the fields.

Here below the class used to replicate the case. I followed what documented in the page http://www.entityframeworktutorial.net/code-first/foreignkey-dataannotations-attribute-in-code-first.aspx

   // Child
    public class Student
    {
        [Autoincrement]
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public int FromId { get; set; }
        public Standard StandardFrom { get; set; }
        public int ToId { get; set; }
        public Standard StandardTo { get; set; }
    }

    // Parent
    public class Standard
    {
        public int StandardId { get; set; }
        public string StandardName { get; set; }
        [ForeignKey("FromId")]
        public ICollection<Student> Students { get; set; }
        [ForeignKey("ToId")]
        public ICollection<Student> StudentsTo { get; set; }
    }

The sql generated is:
CREATE
	TABLE
		"Students" ([StudentID] INTEGER PRIMARY KEY AUTOINCREMENT,
		[StudentName] nvarchar,
		[FromId] int NOT NULL,
		[ToId] int NOT NULL,
		[StandardFrom_StandardId] int,
		[StandardTo_StandardId] int,
		FOREIGN KEY (StandardFrom_StandardId) REFERENCES "Standards"(StandardId),
		FOREIGN KEY (StandardTo_StandardId) REFERENCES "Standards"(StandardId),
		FOREIGN KEY (FromId) REFERENCES "Standards"(StandardId) ON 		DELETE			CASCADE,
		FOREIGN KEY (ToId) REFERENCES "Standards"(StandardId) ON  	DELETE			CASCADE);

CREATE
	INDEX "IX_Student_FromId" ON
	"Students" ("FromId");

CREATE
	INDEX "IX_Student_ToId" ON
	"Students" ("ToId");

CREATE
	INDEX "IX_Student_StandardFrom_StandardId" ON
	"Students" ("StandardFrom_StandardId");

CREATE
	INDEX "IX_Student_StandardTo_StandardId" ON
	"Students" ("StandardTo_StandardId");

What I would have expected is two index a none of the followed columns (StandardFrom_StandardId, StandardTo_StandardId) 

Is it correct?

**Comment by msallin** [comment]
Indices are automatically created for foreign keys by default. To prevent this you can remove the convention ForeignKeyIndexConvention.

**Comment by WonderGnagno** [comment]
Hi Marc,
thank for your support.

Here below what i need in sql;

create table parent(id NUMBER PRIMARY key);

create table child(
id NUMBER PRIMARY key,
idparentleft number ,
idparentright number,
 FOREIGN KEY (idparentleft ) REFERENCES "parent"(Id) ON DELETE CASCADE
 FOREIGN KEY (idparentright) REFERENCES "parent"(Id) ON DELETE CASCADE
);

insert into parent values(1);
insert into parent values(2);
insert into parent values(3);


insert into child values(1, 1, 2);
insert into child values(2,2, 1);
insert into child values(3,3, 2);

delete from parent where id = 1;

select count(*) from child; -- return 1 record

BR
Enrico
________________________________
Da: Marc Sallin <notifications@github.com>
Inviato: sabato 27 ottobre 2018 15:57
A: msallin/SQLiteCodeFirst
Cc: WonderGnagno; Author
Oggetto: Re: [msallin/SQLiteCodeFirst] Double foreign Keys (#135)


The two indicies "IX_Student_StandardFrom_StandardId" and "IX_Student_StandardTo_StandardId" are created by default (as for every FK). You just want to have ON DELETE CASCADE, this is why you apply your own indicies, is this correct?

**Comment by msallin** [comment]
Hi Enrico

I edited the answer. Sorry for the confusion.
Please check again.

Marc

**Comment by msallin** [comment]
I close the issue due to inactivity. Feel free to reopen it, if there are additional questions.
