### ISSUE TITLE
Create, Drop and Recreate the same database

### ISSUE THREAD

**Issue by WonderGnagno** [msallin/SQLiteCodeFirst#142]
Hi,
I've a problem on recreating a database already created and dropped. The new database result to be a 0 file length

In attach, the project the replicate the problem.

is it a bug or a my mistake?

BR
Enrico

[TestEF.zip](https://github.com/msallin/SQLiteCodeFirst/files/2942596/TestEF.zip)

**Comment by msallin** [comment]
Hi Enrico

The problem is, that the initializer is only called once per AppDomain.
See here: https://entityframework.net/knowledge-base/49175225/onmodelcreating-only-called-once-even-for-new-contexts
What do you want to achieve? Why you want to delete the db file? Is truncate the tables alternative?

Regards Marc

**Comment by WonderGnagno** [comment]
Hi Marc,

in some cases i need to drop physically the database because i don't need it anymore. But, in some circumstances, i need to recreate it.
This bring my application to create the same database.

Reading the https://docs.microsoft.com/en-us/dotnet/api/system.data.entity.database.delete?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DEN-US%26k%3Dk(System.Data.Entity.Database.Delete);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.7.1);k(DevLang-csharp)%26rd%3Dtrue&view=entity-framework-6.2.0

seems that the Database.Delete is what i need but calling the method it throws the exception "DeleteDatabase is not supported by the provider."

Now, I found a trick to add a check on the constructor that bring EF to force the creation.

  public MyDbContext(string name) : base(
            new SQLiteConnection($"data source = {name}; foreign keys=true;BinaryGUID=False;"), true)
        {
            if (!File.Exists(name)) Database.Initialize(true);
        }

BR
Enrico




________________________________
Da: Marc Sallin <notifications@github.com>
Inviato: venerdì 8 marzo 2019 06:50
A: msallin/SQLiteCodeFirst
Cc: WonderGnagno; Author
Oggetto: Re: [msallin/SQLiteCodeFirst] Create, Drop and Recreate the same database (#142)


Hi Enrico

The problem is, that the initializer is only called once per AppDomain.
See here: https://entityframework.net/knowledge-base/49175225/onmodelcreating-only-called-once-even-for-new-contexts
What do you want to achieve? Why you want to delete the db file? Is truncate the tables alternative?

Regards Marc

**Comment by msallin** [comment]
Hello Enrico

Glad to see, that you found a solution.

Regards Marc

**Comment by CADbloke** [comment]
Thanks @WonderGnagno - I was having exactly the same problem, fatal crash if the database file was deleted/renamed while the app was running. If nothing else, this will stop a few crashes.

lol - the doc comments for `Intialize` actually say "If "force" is set to true, then the initializer is run regardless of whether or not it has been run before.  This can be useful if a database is deleted while an app is running and needs to be reinitialized."

Good find Enrico.

**Comment by CADbloke** [comment]
Yay edge-cases. In this case, a zero-length database file. My extra codez ...

````c#
try
{
    // fix for zero-length database followed by FATAL crash when the Db is deleted / renamed while the app is running.
    // https://github.com/msallin/SQLiteCodeFirst/issues/142#issuecomment-470935992
    if (!File.Exists(databasePath))
    {
        App.Log.Information("No Database. Intiliazing new Database: {DbPath}", databasePath);
        Database.Initialize(true);
    }
    else
    {
        var info = new System.IO.FileInfo(databasePath); // will create a new file if it doesn't exist

        if (info.Length < 5000) // an empty database is 72kB, this is checking for zero-length files, really.
        {
            App.Log.Information("Invalid Database file Size: {DbFileSize}. Intializing new Database: {DbPath}", info.Length, databasePath);
            Database.Initialize(true);
        }
    }
}
catch (Exception ex)
{
    App.Log.Error(ex, "Broke doing DbContext checking file: {DbPath}", databasePath);
}
````
