### ISSUE TITLE
Nuget package for .net Core

### ISSUE THREAD

**Issue by CBke** [msallin/SQLiteCodeFirst#143]
Hi Marc

Microsoft released EF 6.3 (preview) with .Net Core support.

https://devblogs.microsoft.com/dotnet/announcing-entity-framework-6-3-preview-with-net-core-support/

Are you planning to create a .Net Core version in the future?

Greetings CBke

**Comment by msallin** [comment]
Hello CBke

Thanks for your question.

Yes, I will create a package for netstandard2.1, as soon as EF 6.3 is released and AppVeyor (Build Server) supports netstandard2.1

Greetings Marc

**Comment by msallin** [comment]
Blocked by: https://system.data.sqlite.org/index.html/tktview/ad28d8e026c4c2275547a58bac3fe426ead63faa

Follow up in 30 days.

**Comment by msallin** [comment]
Bug in System.Data.SQLite has been fixed and will be released with v1.0.113.0. Waiting for that release to continue the work on this issue.

**Comment by ReneRam** [comment]
Hi Marc,
I'm currently migrating an application that uses SQLiteCodeFirst in .net Standard to .net Core. going through GitHub I think the release to install is 1.6.0, but I haven't been able to download/update the package either through `PM> Install-Package SQLite.CodeFirst -Version 1.6.0` or in Visual Studio.
Greetings René

**Comment by msallin** [comment]
The necessary version of SQLite isn't yet released. Therefore, this Library doesn't have a assembly which can be used with .NET Core

**Comment by msallin** [comment]
The release  v1.0.113.0 is scheduled for February 2020: 
https://system.data.sqlite.org/index.html/doc/trunk/www/news.wiki

**Comment by msallin** [comment]
The release v1.0.113.0 was rescheduled for March 2020.

**Comment by msallin** [comment]
The release v1.0.113.0 was rescheduled for April 2020.

**Comment by icnocop** [comment]
The release v1.0.113.0 was rescheduled for May 2020.

**Comment by axelheer** [comment]
The release v1.0.112.1 seems to resolve this?

**Comment by msallin** [comment]
@axelheer where do you see this version?
The latest release is 1.0.112 (see https://www.nuget.org/packages/System.Data.SQLite)

It doesn't work. Start SQLite.CodeFirst.NetCore.Console from https://github.com/msallin/SQLiteCodeFirst/tree/%23143

**Comment by axelheer** [comment]
They seem to just updated https://www.nuget.org/packages/System.Data.SQLite.EF6

It's not very clear to me too, what the actually fixed, but I'll look into it since I've got it working within one of my projects.

Edit: now that's weird. I can fix it using Version 1.0.112, but Version 1.0.112.1 won't work. I'll prepare a PR...

**Comment by axelheer** [comment]
Update: now, with Version 1.0.112.2 the required `Configuration` class becomes much cleaner.

**Comment by msallin** [comment]
@axelheer thanks for your contribution. The I merged your PR and released v1.6.0

- https://github.com/msallin/SQLiteCodeFirst/releases/tag/v1.6.0.30
- https://www.nuget.org/packages/SQLite.CodeFirst/1.6.0.30
