### ISSUE TITLE
Feature Request: Drop database if seed values change

### ISSUE THREAD

**Issue by Schwenkner** [msallin/SQLiteCodeFirst#146]
Is it easy to add seed values into consideration if a database is changed?
The database shall be dropped not only when the model is changed, but also when seed data has been changed.

**Comment by msallin** [comment]
Hi

You can derive from `SqliteInitializerBase` to create your own initializer. Look at the `SqliteDropCreateDatabaseWhenModelChanges` ([to the code](https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/Public/DbInitializers/SqliteDropCreateDatabaseWhenModelChanges.cs)) to see how this could look like.

Before I consider to add such an initializer to the library, I would like to hear a bit more about the use case. 
I assume that the seed is defined in code (using the Seed-method) from a initializer and the seed isn't allowed to be changed, correct? What's the point of having it in the database and not directly as code?

**Comment by Schwenkner** [comment]
Yes, the behavior you drscribed ks correct. The usecase is, we store config values in a database, they should have initial values in case the database is created.

**Comment by msallin** [comment]
Hello Schwenkner

I'm not sure if I understand correctly. 

In the initial text I understand, that the whole database should be dropped, if the seed value in code doesn't correspond to the values in the database (due to a change in code or in the database). However, in the second answer you state "config values with initial values", which is actually how seeding works.

Can you please exactly describe how this feature is supposed to work?
Feel free to answer in german.

Cheers, Marc

**Comment by Schwenkner** [comment]
Ok, let me explain.

One table in the database is used to store configuration values. These values can be modified later by the user, but the database must be deploeyed with default values. For these values I will use seed values. So far so good.

Now we decide to change one default config value (a seed value). As I understood, for a table a hash value of the columns is stored in an extra table. Thus, if changing the a dataset it could be recognised and the table can be dropped.

What I want is, to store not only the table structure as a hash value, but also the full newly created table, inluding the seed values. In the method to determine the changes, a table must be created in memory, filled with the seed values and compared with the stored hash. If this differs, then either the table structure or a seed value was changed. This results in dropping the table. And yes, user changed values will get lost, unless we have no migration support.

**Comment by CADbloke** [comment]
I would prefer to not have a standard behaviour that destroys any part of production database if a seed value changes. This is non-typical behaviour that you should manage externally to this library.

**Comment by msallin** [comment]
Thank you for your explanation. I agree with @CADbloke and in addition, I do not believe that this behavior will be used a lot.

Thus, I will not implement such an initializer as part of this project. However, the base initializer is created in a extensible way, ready to get inherited. You should be able to implement the desired behavior on your own.

See https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/Public/DbInitializers/SqliteInitializerBase.cs
