### ISSUE TITLE
Why need EntityFramework.SqlServer.dll?

### ISSUE THREAD

**Issue by LeiYangGH** [msallin/SQLiteCodeFirst#149]
The project is greate and after clone with .net 4.5 and vs2019 I can run all the tests and the console sample successfully.

But I don't understand why **EntityFramework.SqlServer.dll** is always in the **output** directory. The assemly is not in the 'references' list, and I **removed** the sqlserver related sections in `app.config`. After build, the dll is there again!

The I **removed** the dll in the output folder, and run the exe directly, no error and the database created successfully.

So why need it?

**Comment by msallin** [comment]
This is due to a reference of the EntityFramework NuGet package.

![image](https://user-images.githubusercontent.com/7792779/80281606-a8d35180-870c-11ea-9772-12c891f2eded.png)
