### ISSUE TITLE
Question - What are the steps required?

### ISSUE THREAD

**Issue by Franck-E** [msallin/SQLiteCodeFirst#154]
I am sorry for asking, but it seems a bit confusing at first. Is there steps available by a chance?

Like for example:
1 - install package
2 - set connection string
3 - set datasource

Not fully sure how to use it... :(
Thanks in advance.

**Comment by msallin** [comment]
Hello

See "How to use" in the README. https://github.com/msallin/SQLiteCodeFirst#how-to-use
The only step specific for this library is setting the initializer.

Greetings, Marc

**Comment by Franck-E** [comment]
Thank you, I actually figured it out .. :)
I thought this was a package that would install all other packages, like:
entity framework
system.data.sqlite
and so on, until I realize.. 

Many thanks anyway for your reply :)
