### ISSUE TITLE
SetInitializer Instance Reference issue

### ISSUE THREAD

**Issue by Snuffsis** [msallin/SQLiteCodeFirst#155]
Following the How To Use on the readme results in an error for my project.
Project is targetting 4.8 (which is listed as supported?)
And the code for OnModelCreating is a straight copy from the How To Use section.

```
protected override void OnModelCreating(DbModelBuilder modelBuilder)
{
	var sqliteConnectionInitializer = new SqliteCreateDatabaseIfNotExists<DbContext>(modelBuilder);
	Database.SetInitializer(sqliteConnectionInitializer);
}
```

But this results in an error on the Database.SetInitializer(sqliteConnectionInitializer) line.

**Comment by Snuffsis** [comment]
Found Solution:
Have to fully specify the name of the type as such
`System.Data.Entity.Database.SetInitializer(sqliteConnectionInitializer);`

**Comment by nicolasr75** [comment]
> Found Solution: Have to fully specify the name of the type as such `System.Data.Entity.Database.SetInitializer(sqliteConnectionInitializer);`

This should definitely be added to the example code on the main page!
