### ISSUE TITLE
Autoincrement Fail With Key multiple

### ISSUE THREAD

**Issue by NeoKabamaru** [msallin/SQLiteCodeFirst#161]
Example:

 public class Base
    {
      [Autoincrement]
        [Key, Column(Order = 0)]
        public int Id { get; set; }
    }

 public class Comment : Base
    {
        [Key, Column(Order = 1)]
        public int MaterialId { get; set; 
    }

In this case. Table "Comments" are generated with both keys, but in isn't autoincrement

**Comment by NeoKabamaru** [comment]
I have found the following information:

https://stackoverflow.com/questions/6154730/sqlite-multi-primary-key-on-a-table-one-of-them-is-auto-increment


I think that's what I want to do, and it's not possible ...
Any solution?

**Comment by msallin** [comment]
Hi

Well, there are always three things to consider.
1. What is supported by EF (by the model and at runtime)?
2. What SQL code should be generated?
3. What is supported by SQLite?

Please try to write (and execute) the DDL statements by hand which you would expect to be generated. Then use the resulting structure with your EF model.  That makes sure that EF and SQLite supports this and by handing over the expected DDL code, I can adjust the library to emit it based on the information in code.

**Comment by NeoKabamaru** [comment]
Hi,

Thanks for your fast answer.

I will follow your advice and try.

The problem really is not that part of the key is self-incrementing.
The problem would be that putting the annotation "[Autoincrement]" automatically assumes that said value will be key, when it might not be necessary (as in my case).

I'm also checking your code in case I could find the solution, so I can tell you later.

Greetings.

**Comment by msallin** [comment]
Closed due to inactivity.
