### ISSUE TITLE
add .NET Standard 2.0 target

### ISSUE THREAD

**Issue by billzhuang** [msallin/SQLiteCodeFirst#167]
hello, 
base on Microsoft suggestion, https://docs.microsoft.com/en-us/dotnet/standard/net-standard#which-net-standard-version-to-target

target to .NET Standard 2.0 will cover most case, from 4.7.2 to .NET 6

**Comment by msallin** [comment]
What use case will be covered when I target .NET Standard 2.0 instead of 4.5 and .NET Standard 3.1?
It simplifies the build/release/package, but this is automated anyway.

**Comment by billzhuang** [comment]
theoraticly it's same, but .NET Standard 2.0 is a bridge between 4.x to Core to .Net 5/6

I think most complicated thing is EF6 also only support Standard 2.1.

there is a issue in EF6, https://github.com/dotnet/ef6/issues/1571

so it's not possible for this repo to support .NET Standard 2.0

but again, tks for your repo, help me a lot.

**Comment by msallin** [comment]
Ah.. True.. That was the reason I didn't add dotnet standard 2.0
