### ISSUE TITLE
Unable to create two child tables from a single parent table with one-to-many relation on both

### ISSUE THREAD

**Issue by gchernis** [msallin/SQLiteCodeFirst#21]
Here's the error:

```
Test 'WhenPersistingSQLite' failed: System.Data.SQLite.SQLiteException : SQL logic error or missing database
index IX_Branch_ID already exists
    at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
    at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
    at System.Data.SQLite.SQLiteDataReader.NextResult()
etc.
```

And here's the code to reproduce (uses F# to declare types, NUnit to drive test):

```
open System.Collections.Generic
open System.Linq

type Leaf() =
   member val ID = -1 with get,set

type Bud() =
   member val ID = -1 with get,set

type Branch() =
   member val ID = -1 with get,set
   member val Leaves = List(Enumerable.Empty<Leaf>()) with get,set
   member val Buds = List(Enumerable.Empty<Bud>()) with get,set

=======
   [TestFixture]
   public class Tests
   {
      [Test]
      public void WhenPersistingSQLite()
      {
         using (var dbContext = new TreeSqliteDBContext())
            dbContext.TreeDbSet.Add(new Branch());
      }
   }

   public class TreeSqliteDBContext : DbContext
   {
      public DbSet<Branch> TreeDbSet { get; set; }

      protected override void OnModelCreating(DbModelBuilder modelBuilder)
      {
         var connString = Database.Connection.ConnectionString;
         Database.SetInitializer(new SqliteDropCreateDatabaseAlways<TreeSqliteDBContext>(
            connString, modelBuilder));
      }
   }
```

**Comment by msallin** [comment]
Thanks for filing the bug.

**Cause**
Your Code will create the following SQL Statements:

```
CREATE TABLE Branch ([ID] INTEGER, PRIMARY KEY(ID));
CREATE TABLE Bud ([ID] INTEGER, [Branch_ID] int, PRIMARY KEY(ID), FOREIGN KEY (Branch_ID) REFERENCES Branch(ID));
CREATE TABLE Leaf ([ID] INTEGER, [Branch_ID] int, PRIMARY KEY(ID), FOREIGN KEY (Branch_ID) REFERENCES Branch(ID));

CREATE  INDEX IX_Branch_ID ON Bud (Branch_ID);
CREATE  INDEX IX_Branch_ID ON Leaf (Branch_ID);`
```

This will result in two indices with the same name and therefore the message "index IX_Branch_ID already exists".

**Workaround**
The convention `ForeignKeyIndexConvention` is responsible to create indicies for ForeignKeys.
So you can simply remove this convention by using `modelBuilder.Conventions.Remove<ForeignKeyIndexConvention>();`

**Bugfix**
I'll rethink/rewrite the Index name generation to fix this bug.
As soon as done I'm going to release the version "v0.9.5.1" which contains the fix.

**Comment by msallin** [comment]
**Update**
I just tried to rewrite the index name generation and I learned that the index name is already generated by the `ForeignKeyIndexConvention` (I only generate the index name if there is no name for this index specified). My current plan is to replace the `ForeignKeyIndexConvention` by my own convention `SqliteForeignKeyIndexConvention` which will be almost the same expect from the name generation. May I'll use inheritance or reverse engineer the `ForeignKeyIndexConvention`-Class.

This will result in more work than expected so please use the workaround (comment above) until the bug is fixed. If you need indicies on the ForeignKeys you can still create them manual by using the `[Index]`-Attribute.

**Comment by gchernis** [comment]
I used the workaround and it seems to work OK.  Thank you for a speedy response!

**Comment by msallin** [comment]
I started with coding a while ago.
The Code is here but not yet ready.
Feel free to grap it and continue:
https://github.com/msallin/SQLiteCodeFirst/tree/Issue_21

**Comment by msallin** [comment]
https://github.com/msallin/SQLiteCodeFirst/pull/39
