### ISSUE TITLE
Please support unique attribute

### ISSUE THREAD

**Issue by HarelM** [msallin/SQLiteCodeFirst#27]
Can you please support unique attribute on properties?

**Comment by msallin** [comment]
What exactly does this attribute and how should it reflect in SQLite SQL Code?

**Comment by HarelM** [comment]
You can check the sqlite documentation, but basically you can set a constraint for a table that does not allow to add an entity if it violates this constraint. For example in your code stadium name can be unique.

**Comment by msallin** [comment]
Started working on it.
Is not as easy as it sounds.
https://github.com/msallin/SQLiteCodeFirst/tree/Issue-27
