### ISSUE TITLE
IndexAttribute for ForeignKeyColumns

### ISSUE THREAD

**Issue by oodoloo** [msallin/SQLiteCodeFirst#28]
The name of an index for foreign key column is always the default. Can you please provide the possibility that the index-name of a foreign will be used, when it's defined?

**Comment by msallin** [comment]
As a workaround you can remove the foreign `ForeignKeyIndexConvention` and add your index manual by using the `index`-attribute.

**Comment by msallin** [comment]
The index name must be unique for the whole database, therefore I will not change the default behavior. As stated above you can remove the convention and implement a own convention.
