### ISSUE TITLE
PluralizingTableNameConvention

### ISSUE THREAD

**Issue by foriequal0** [msallin/SQLiteCodeFirst#30]
PluralizingTableNameConvention is not applied on table creation.
Table names are always same as entity name which generally singular(not plural).

**Comment by msallin** [comment]
Hi,

I guess you are using the sample application.
Then you should remove the line `modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();` in `FootballDbContext.OnModelCreating`.

Greetings Marc

**Comment by foriequal0** [comment]
I faced that error on my own application with `PluralizingTableNameConvention`.

Simple example: (some korean characters in project. sorry.)
https://github.com/foriequal0/SQLiteCodeFirst_Pluralizing 
I used VS2010, .NET40, EntityFramework 6.1.0, System.Data.SQLite.EF6 1.0.97.0

When running the example in debug mode, an error is thrown as the following.
`"{"SQL logic error or missing database\r\nno such table: Nouns"}"`

Though sqlite file was created after the error, there's only "Noun" table inside, while I expect that there should be "Nouns" table because that `PluralizingTableNameConvention` was default configuration.
The table schema was `CREATE TABLE Noun ([Word] nvarchar (128) NOT NULL, [Meaning] nvarchar, PRIMARY KEY(Word)`.

I guess SQLiteCodeFirst always create table with singular entity name, and removing `PluralizingTableNameConvention` prevents EF from querying with plural name.

I've also checked sample application after you've commented. (BTY, I had to manually modify some header line in .sln to open with my older VS2010, and lower SQLite.CodeFirst.Console's Framework to 4.0 to build.)
Removed line `modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();`, same error  was thrown "no such table: Stadions". Table was created with "Stadion", EF queries "Stadions" because "PluralizingTableNameConvention" was the configuration.

Can you check this issue with your environment?

Thank you.
