### ISSUE TITLE
Error when using FK Constraints with PluralizingTableNameConvention

### ISSUE THREAD

**Issue by msallin** [msallin/SQLiteCodeFirst#43]

**Comment by misterbauer** [comment]
I was pulling my hair out trying to figure out why my project wouldn't work with plural table names. I should've looked here first! :+1:

**Comment by sm-g** [comment]
Seems fix for this still not in 0.9.8 nuget.

**Comment by msallin** [comment]
Hi,

This fix will be included the next release (see milestone - v1.0.0.0).
Thats why this issue is not yet closed.
Anyway its already merged into the master branch.
If you need this fix you can build the master branch by yourself or you can get it from the last CI-Build:
https://ci.appveyor.com/project/msallin/sqlitecodefirst/build/CI_master_76/artifacts

Greetings Marc
