### ISSUE TITLE
Database is not created if it is in an folder which doesn't exists

### ISSUE THREAD

**Issue by mprattinger** [msallin/SQLiteCodeFirst#45]
Hi,

thanks for the great tool.

I noticed, that if the connection string contains folder, which doesn't exist, the database is not created if you use SqliteCreateDatabaseIfNotExists or SqliteDropCreateDatabaseAlways.
For example the connstring maybe .\data\user.sqlite.

r Michael

**Comment by yeganehaym** [comment]
hi and thank for this great source
nuget is update for this?
because the version of there is 0.9.8 yet
i will be appreciate if you update there too
thanks again

**Comment by msallin** [comment]
Hi @ yeganehaym 

Right, the NuGet package version is 0.9.8.
The next milestone will be v1.0.0 and I'm currently working on the issues for this milestone.
Check out the issues here:
https://github.com/msallin/SQLiteCodeFirst/milestones/v1.0.0.0

Greetings
