### ISSUE TITLE
Can not configure the table name.

### ISSUE THREAD

**Issue by linqingfeng** [msallin/SQLiteCodeFirst#47]
The following code,

protected override void OnModelCreating (DbModelBuilder modelBuilder)
{
modelBuilder.Entity <DictionaryTimestamp> () ToTable ("Base.DictionaryTimestamp");

var sqliteConnectionInitializer = new SqliteCreateDatabaseIfNotExists <TDbContext> (modelBuilder);
Database.SetInitializer (sqliteConnectionInitializer);
}

Table name and the entity name mapping is not the same, but still with the name of the table created entity name, is still a "DictionaryTimestamp", rather than "Base.DictionaryTimestamp"
Is there a solution?

Thank you very much!

**Comment by msallin** [comment]
Well, I just hacked around some hours to investigate this problem.

_Problem 1:_
If you use "Base.DictionaryTimestamp" as tableName then SQLite will interpret "Base" as the database and therefore it will fail.
To use a dot you have to use either [] or "" around your tablename.
To to this correctly with the entity framework you specifiy a schema.
E.g. this way:
modelBuilder.Entity<Team>().ToTable("MyTable", "mySchema")

_Problem 2:_
Currently this library does not support the use of schemas.
I implemented it to test whether it will fix your issue.
The generation works as it should. BUT the entity framework will not use this schema to construct the table name, so its not possible to use the database with the entity framework.

_Solution_
To make it easy I wrap all input (names of tables, names of indicies) with " ".
I'll release it with v1. There is a branch "issue-47" which contains this fix.
You can grap it and create a working version for you, in the meantime.

**Comment by linqingfeng** [comment]
Thanks for your patience answer ^_^
