### ISSUE TITLE
Timespan properties

### ISSUE THREAD

**Issue by sm-g** [msallin/SQLiteCodeFirst#49]
I want to use Timespan properties with EF6 without mapping them to int64, as with SqlServer DB, but get `There is no store type corresponding to the EDM type 'Edm.Time' of primitive type 'Time'`. Found [this SO question](http://stackoverflow.com/questions/32097637/sql-lite-throwing-system-notsupportedexception-for-time-data-type-in-sql) about problem.

Any solutions?

**Comment by msallin** [comment]
Hi,

I looked into this.
It seems that this is a problem with SQLite + EF6 and not with the generation of the database.
Please check the system.data.sqlite support options:
https://system.data.sqlite.org/index.html/doc/trunk/www/support.wiki

Greetings Marc
