### ISSUE TITLE
InMemoryConnectionString throwing exception

### ISSUE THREAD

**Issue by Alantod17** [msallin/SQLiteCodeFirst#56]
When I am trying to run the project with in memory connection string the following exception is threw：“The given key was not present in the dictionary.”

My connection string like: 

<add name="footballDb" connectionString=":memory:;foreign keys=true" providerName="System.Data.SQLite" />

Possible to make the code work with in memory connection string?

Cheers
D

**Comment by msallin** [comment]
Could you please post the connection string you use?

**Comment by HarelM** [comment]
We use the following classes in order to avoid the usage of app.config file, which in turn makes the connection string be in-memory.

``` cs
    /// <summary>
    /// this is used only for .Net 4 - remove this class when going to .Net 4.5 
    /// </summary>
    public class DotNet4FactoryResolver : IDbProviderFactoryResolver
    {
        public DbProviderFactory ResolveProviderFactory(DbConnection connection)
        {
            if (connection is SQLiteConnection)
            {
                return SQLiteProviderFactory.Instance;
            }
            if (connection is EntityConnection)
            {
                return EntityProviderFactory.Instance;
            }
            // should not reach here
            return null;
        }
    }

    public class SQLiteConnectionFactory : IDbConnectionFactory
    {
        public DbConnection CreateConnection(string nameOrConnectionString)
        {
            return new SQLiteConnection(nameOrConnectionString);
        }
    }

    /// <summary>
    /// This class is used in order to override the app.config settings for sqlite.
    /// </summary>
    public class SQLiteConfiguration : DbConfiguration
    {
        public SQLiteConfiguration()
        {
            SetDefaultConnectionFactory(new SQLiteConnectionFactory());
            SetProviderFactoryResolver(new DotNet4FactoryResolver());
            SetProviderFactory("System.Data.SQLite.EF6", SQLiteProviderFactory.Instance);
            Type sqliteProviderServicesType = Type.GetType("System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6");
            FieldInfo fieldInfo = sqliteProviderServicesType.GetField("Instance", BindingFlags.NonPublic | BindingFlags.Static);
            var sqliteProviderServicesInstance = (DbProviderServices)fieldInfo.GetValue(null);
            SetProviderServices("System.Data.SQLite.EF6", sqliteProviderServicesInstance);
        }
    }
```

and then in the database context we use the following attribute:

``` cs
    [DbConfigurationType(typeof(SQLiteConfiguration))]
    public abstract class SqLiteDatabaseContext : DbContext
    {
...
    }
```

**Comment by Alantod17** [comment]
Thanks for the reply 

following is my connection string looks like
`<add name="LentuneDatabase" connectionString="Data Source=:memory:;Version=3;New=True;" providerName="System.Data.SQLite.EF6" />`

the program was fine when i use the connection string with local file
`<add name="LentuneDatabase" connectionString="Data Source=C:\temp\LentuneTest.sqlite" providerName="System.Data.SQLite.EF6" />`

we would like to use sqlite as a in memory DB for our integration testing, needs create database based on the models 
Please help.

Cheers
D

**Comment by msallin** [comment]
This library was not designed with the in memory approach in mind.
I assume that this in memory connection string works when you use the db-first approach, right?
If yes, then you could use the class SqliteDatabaseCreator or SqliteSqlGenerator manually to build up the database.

The classes:
https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/SqliteSqlGenerator.cs
https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/SqliteDatabaseCreator.cs

For an example how to use it:
https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/DbInitializers/SqliteInitializerBase.cs

Edit: 
Make sure that you are using the latest version of this library, else these two classes are not exposed.

**Comment by msallin** [comment]
@Alantod17 were you able to get this work?

**Comment by Alantod17** [comment]
@msallin Thanks for the follow up. 

No, we are switch to EF7's in memory DB since we do not want to build up DB manually and maintain it.
