### ISSUE TITLE
CreateDrop database multiple times

### ISSUE THREAD

**Issue by AndersMalmgren** [msallin/SQLiteCodeFirst#57]
Hi,
I want to use SQLiteCodefirst to create my unist test database to test my EF6 domain.
Problem is that OnModelCreating is only called once per app domain, and you cant disable model caching.

Is there a way to use SQLLite code first for setting up the database for each test?

**Comment by msallin** [comment]
Hello 

What means "each test"?
What exactly you want test?

I've also a bunch of unit tests (NUnit) which are using SQLite as a database.
I'm using it with the DropCreateDatabaseAlways Initializer. So there is a there is a database per TestFixture.

If you want to delete the database file check the "DeleteDatabase" method here:
https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/DbInitializers/SqliteDropCreateDatabaseWhenModelChanges.cs

Here is how you could force that the model is not cached:
http://stackoverflow.com/questions/13493199/onmodelcreating-forcing-new-creation

Greetings Marc

**Comment by msallin** [comment]
Close due to inactivity.
Please reopen if the issue still exists and provide additional information.
