### ISSUE TITLE
Initialize the database when the individual can only create or delete a table?

### ISSUE THREAD

**Issue by linqingfeng** [msallin/SQLiteCodeFirst#58]
Hi,

You add a new initialization function "SqliteDropCreateDatabaseWhenModelChanges" Very Good!

Please can further refine this feature, go to "table-level"?

Logic is as follows,
1. When the time change Model (Model name does not change, but changes in the field), do not delete the database, but only delete the table, then rebuild.
2. If a new Model, the Model corresponding to the new table.
3. If the Model delete, delete the Model corresponding table.

thank you very much!

**Comment by msallin** [comment]
Hello 

Thanks for your submission.
That will result in comparing SQL strings.
So of course it would be possible but really error-prone.
Please have  alook at the issue #4 which is about migrations.
That will enable such scenarios.

Thanks Marc
