### ISSUE TITLE
Seeding with ContextInitializer

### ISSUE THREAD

**Issue by code1line** [msallin/SQLiteCodeFirst#6]
Unfortunately, the seeding does not work - but no exception and also no data.
Suggestions?

**Comment by msallin** [comment]
Seed is only be executed if the database is generated from scratch. In fact File.Exists is used to check whether the db file exists. If the file exists, the initializer assumes that there is a database and the generation/execution of the SQL DDL Code and the seeding is skipped. May this is the problem?

**Comment by msallin** [comment]
Do you call `SaveChanges()` on the context? At the moment you have to do this by your own. But I agree if this is not as expected, because I just saw that I was missing this call also in the test app :)
I'll add the functionality to call `SaveChanges()` automatically after seeding.

**Comment by code1line** [comment]
Works!
