### ISSUE TITLE
Incorrect Self-Referencing FK created in special case entity names

### ISSUE THREAD

**Issue by jjbutera** [msallin/SQLiteCodeFirst#69]
This is a weird one in version 1.2.3.15. If you have an entity that begins with the plural of another entity, and it has a navigation property to that other entity, the FK is created incorrectly. Try the following:

```
public class Foo
{
    public int FooId { get; set; }
    public string Name { get; set; }

    private ICollection<FooStep> _FooSteps;
    public virtual ICollection<FooStep> FooSteps
    {
        get { return _FooSteps ?? (_FooSteps = new HashSet<FooStep>()); }
        set { _FooSteps = value; }
    }
}

public class FooStep
{
    public int FooStepId { get; set; }
    public int FooId { get; set; }
    public int Number { get; set; }
    public virtual Foo Foo { get; set; }
}
```

When the database is generated, instead of a FK to FooId being created in table FooSteps, it's created on the Foos table instead (so it ends up with a self-referenced FK). Weird!

Note: I did not encounter this behavior in 1.2.2.14. It looks like the patch to support small entity names introduced this new bug.

If you change FooStep to anything else that doesn't have an "S" after Foo, then it generates fine. This generates the FK as expected on the FoobSteps table:

```
public class FoobStep
{
    public int FoobStepId { get; set; }
    public int FooId { get; set; }
    public int Number { get; set; }
    public virtual Foo Foo { get; set; }
}
```

**Comment by jjbutera** [comment]
**CORRECTION**. I can actually reproduce this in 1.2.2.14 as well. Of course, you'll have to use the entity names Foooo and FooooStep to bypass the short name bug. Oddly enough, I have some entities where this does not occur. For example, I have an entity called Scene and SceneSlave where this does not occur. The only difference I can see is that SceneSlave has more than one navigation property whereas the entities for which I see this behavior only have the one.

**UPDATE**  The IsSelfReferencing() check is, indeed, the culprit. This happens when the referencing entity name follows this pattern [EntityName][anything 4 characters]. When this occurs, the assocation is determined to be self-referencing which is not the case. I'm going to create a true self-referencing entity association to see how to permanently fix IsSelfReferencing(). Stay tuned...

**UPDATE 2** After creating an actual self-referencing entity with more than one self-referencing column, the association types are always [EntityName] and [EntityName]Self. The easiest fix which is working for me is:

```
    private static bool IsSelfReferencing(AssociationType associationType)
    {
        string to = associationType.Constraint.ToRole.Name;
        string from = associationType.Constraint.FromRole.Name;

        return to == $"{from}{SelfReferencingPostfix}";
    }
```

However, this does ignore an edge case....what if you have an entity called FooSelf that has a FooId reference? I tested this, and IsSelfReferencing will incorrectly return true with the above code. I've been sniffing out AssocationType to see if there is any possible way to determine when the association is a self reference by any other means than querying the ToRole and FromRole name. I haven't found one yet.

**UPDATE 3** This seems to do the trick:

```
    private static bool IsSelfReferencing(AssociationType associationType)
    {
        return ((RefType)associationType.Constraint.ToRole.TypeUsage.EdmType).ElementType.Name ==
        ((RefType)associationType.Constraint.FromRole.TypeUsage.EdmType).ElementType.Name;
    }
```

It can be tested with the following entities:

```
public class Foo
{
    public int FooId { get; set; }
    public string Name { get; set; }

    public int? FooSelf1Id { get; set; }
    public int? FooSelf2Id { get; set; }
    public int? FooSelf3Id { get; set; }

    [ForeignKey("FooSelf1Id")]
    public virtual Foo ParentMyEntity1 { get; set; }

    [ForeignKey("FooSelf2Id")]
    public virtual Foo ParentMyEntity2 { get; set; }

    [ForeignKey("FooSelf3Id")]
    public virtual Foo ParentMyEntity3 { get; set; }

    private ICollection<FooStep> _FooSteps;
    public virtual ICollection<FooStep> FooSteps
    {
        get { return _FooSteps ?? (_FooSteps = new HashSet<FooStep>()); }
        set { _FooSteps = value; }
    }

    private ICollection<FooSelf> _FooSelves;
    public virtual ICollection<FooSelf> FooSelves
    {
        get { return _FooSelves ?? (_FooSelves = new HashSet<FooSelf>()); }
        set { _FooSelves = value; }
    }
}

public class FooStep
{
    public int FooStepId { get; set; }
    public int FooId { get; set; }
    public int Number { get; set; }
    public virtual Foo Foo { get; set; }
}

public class FooSelf
{
    public int FooSelfId { get; set; }
    public int FooId { get; set; }
    public int Number { get; set; }
    public virtual Foo Foo { get; set; }
}
```

**Comment by msallin** [comment]
Hello @jjbutera 
Thank you very much for reporting this bug, doing further investigations and providing the code for the fix.

I just released a new version, including the bugfix.
You find on [NuGet](https://www.nuget.org/packages/SQLite.CodeFirst/) or on [GitHub](https://github.com/msallin/SQLiteCodeFirst/releases/tag/v1.2.4.16)

Don't forget to stare the project, if you like it :)

Regards Marc
