### ISSUE TITLE
[Question] DotNetCore Support

### ISSUE THREAD

**Issue by ghost** [msallin/SQLiteCodeFirst#71]
Any plans on DotNetCore support?

**Comment by msallin** [comment]
Hello @hugito00 

Thanks for your question.

SQLite is already supported OOTB by EF Core.
https://docs.efproject.net/en/latest/providers/sqlite/index.html

EF 6.1 does not support .NET Core, so you can not use EF 6.1 neither this lib together with .NET Core.

Basically it would be possible to port this Lib to support EF Core but I don't see a benefit.
How does your scenario looks like?

Greetings

**Comment by ghost** [comment]
Hello, 

Well I did saw that it had a provider for SQLite. Does it support CodeFirst migrations for SQLite out of the box now?
If that's the case my question is kinda pointless indeed.

I was just converting a really small app that I made using this Lib to dotnetcore. I really liked the simplicity. Well gonna take a better look at EF Core.

Thanks.

**Comment by msallin** [comment]
Hi

As far as I know code first/migrations are supported.
How ever, there are some limitations but as my Library only supports code first and not migrations, this should not be a big deal:
https://docs.efproject.net/en/latest/providers/sqlite/limitations.html

Greetings
