### ISSUE TITLE
可不可以加入迁移(Migration)功能？

### ISSUE THREAD

**Issue by woaiwhr001** [msallin/SQLiteCodeFirst#72]
谢谢你的程序，让我们非常方便的使用CodeFirst功能，但是另一个很常见的工能Migration我不知道怎么使用，能不能给点提示，再次感谢。

**Comment by msallin** [comment]
Translated using Google Translate:
"Thank you for your program , so we are very convenient to use CodeFirst function , but another very common workers Migration can I do not know how to use , can give clues , thanks again."

This library does not (yet) support migrations.
For details #4 

Regards Marc
