### ISSUE TITLE
Duplicate Index Error in SQL

### ISSUE THREAD

**Issue by bgoomba** [msallin/SQLiteCodeFirst#75]
In some situations, there is the possibility for the generated sql to contain more than one index with the same name which generates an error.

In my case, I have a table that relates one entity to another and some fields in other tables with the name CaseUpdateId that participates in a foreign key relationship \ entity relationship and the code creates and index for them all with the same  IX_CaseUpdateId name. 

Here one situation where it happens (I originally created the db on Sql Server and moved it to SQLite)

![image](https://cloud.githubusercontent.com/assets/21088887/17751142/03e831b8-6483-11e6-935a-b96f18b84525.png)

 This is the model builder statement that creates the relationships
modelBuilder.Entity<CaseUpdate>()
        .HasMany(e => e.CaseUpdateBatches)
        .WithMany(e => e.CaseUpdates)
        .Map(m =>m.ToTable("BatchCaseUpdates").MapLeftKey("CaseUpdateId").MapRightKey("BatchId"));

modelBuilder.Entity<CaseUpdate>()
      .HasMany(e => e.CaseFieldUpdates)
      .WithRequired(e => e.CaseUpdate)
      .WillCascadeOnDelete(false);

This will result in indexes with the same name.

Not sure how you want to fix it.  In my case, I modified CreateIndexStatementBuilder to add the table name to the index name.  The result is something like IX_TableName_FieldName

**Comment by msallin** [comment]
Could you provide the code you use (just the classes for the entity model)?

**Comment by msallin** [comment]
Closed because the question was not answered.
