### ISSUE TITLE
"table <name>already exists" exception when application restarts

### ISSUE THREAD

**Issue by eliseev-eag** [msallin/SQLiteCodeFirst#83]
Hello. I use your the package for my app. I have created 2 simple classes with many-to-many relationship. In the databasecontext class method OnModelCreating(DbModelBuilder modelbuilder in) I use a class SqliteCreateDatabaseIfNotExists. When the app is first started and the database is not created yet everything works fine, insert and select operations. But when I restart the app, I get 'table <tablename> already exists' exception.

**Comment by msallin** [comment]
Hi @eliseev-eag 
Please upload your solution here https://1drv.ms/f/s!ApmGN3k-vuHIt_NWdNwE-0L_Ruqt5A and I'll have a look.
Cheers

**Comment by eliseev-eag** [comment]
I've uploaded my solution, please check it

**Comment by msallin** [comment]
Delete the space in your connection string.
`<add name="DatabaseContext" connectionString="Data Source = database.sqlite; Version = 3;" providerName="System.Data.SQLite" />`

Correct:
`<add name="DatabaseContext" connectionString="Data Source=database.sqlite; Version = 3;" providerName="System.Data.SQLite" />`

Where the space on the key side (Data Source =) doesn't matter, this space is trimmed.
But the space in the value isn't trimmed, which is correct.

See `ConnectionStringParser`
https://github.com/msallin/SQLiteCodeFirst/blob/master/SQLite.CodeFirst/Internal/Utility/ConnectionStringParser.cs#L37

```
[SuppressMessage("Microsoft.Globalization", "CA1308:NormalizeStringsToUppercase", Justification = "ToUppercase makes no sense.")]
        private static IDictionary<string, string> ParseConnectionString(string connectionString)
        {
            connectionString = connectionString.Trim();
            string[] keyValuePairs = connectionString.Split(KeyValuePairSeperator);

            IDictionary<string, string> keyValuePairDictionary = new Dictionary<string, string>();
            foreach (var keyValuePair in keyValuePairs)
            {
                string[] keyValue = keyValuePair.Split(KeyValueSeperator);
                if (keyValue.Length >= 2)
                {
                    keyValuePairDictionary.Add(keyValue[KeyPosition].Trim().ToLower(CultureInfo.InvariantCulture), keyValue[ValuePosition]);
                }
            }

            return keyValuePairDictionary;
        }
```

**Comment by eliseev-eag** [comment]
Thank you very much for the help!
