### ISSUE TITLE
Support for DefaultValueAttribute

### ISSUE THREAD

**Issue by lingy-Mg** [msallin/SQLiteCodeFirst#84]
[DefaultValue("(datetime('now', 'localtime'))")]

**Comment by msallin** [comment]
Hello

Could you please provide more details?

**Comment by lingy-Mg** [comment]
Hello
Does not support "DefaultValue" now?

English is not very good
Bing translation

**Comment by lingy-Mg** [comment]
`[DefaultValue("(datetime('now', 'localtime'))")]`
`public DateTime CreateTime { get; set; }`

**Comment by lingy-Mg** [comment]
It seems that it hasn't come into effect

**Comment by msallin** [comment]
You are right, this is not supported. 
Please check the ReadMe Page to see whats supported (https://github.com/msallin/SQLiteCodeFirst/blob/master/README.md)

I just had a look at it and I decided to not support it at all.

MSDN states the following:

> You can create a DefaultValueAttribute with any value. A member's default value is typically its initial value. A visual designer can use the default value to reset the member's value. Code generators can use the default values also to determine whether code should be generated for the member.

https://msdn.microsoft.com/en-us/library/system.componentmodel.defaultvalueattribute(v=vs.110).aspx

So in my opinion its not designed for the purpose you want to use it. As this is defined in the the System.ComponentModel this is a general purpose attribute which means that its possible that this is applied in code bases which make use of SQLite.CodeFirst. So it will might break existing code bases.
Furthermore, its possible to use this attribute with a wide range of types e.g. Object, which can not be converted into anything meaningful.
In addition, its also not supported in EF6 CodeFirst.

**Comment by lingy-Mg** [comment]
So how do I set the default value for a database field?

**Comment by msallin** [comment]
Its not possible. I created a new issue for this (#85).
If there is more demand for this feature, may I'll implement it.
When this is required for a commercial project, I can offer a paid implementation.
Of course contributions are welcome, you can also implement this by yourself and create a PR. 
I wrote more details in the new ticket.

**Comment by digocesar** [comment]
I already did it some time! Something like this:

STRFTIME('%d-%m-%Y   %H:%M', 'NOW','localtime')

Google for "sqlite default datetime" that will show something...

**Comment by msallin** [comment]
Hi

Well, of course its possible to use a default value for a SQLite DB. But as I assume that one would like to use Code First when he uses SQLite.CodeFirst, this was not the question.

It's not supported to set a columns default value using SQL with SQLite.CodeFirst.

As stated above, I don't want to support it by using the DefaultValueAttribute but I'm looking forward to accept a PR which adds the default value functionalty by using a custom attribute (see linked issue).

**Comment by digocesar** [comment]
It's possible that I did it using migrations, not in code first attribute. I don't remember now.
