### ISSUE TITLE
Can't set custom PK value

### ISSUE THREAD

**Issue by DiscoDancer** [msallin/SQLiteCodeFirst#87]
Hello.
I've created a table from [class](https://gist.github.com/DiscoDancer/36cc366eb4b48c70b47f06e29691772f).
[Table ](https://gist.github.com/DiscoDancer/7ca810463e7428e7368b5c306258732d)has INT primary key.
When I try to add new object using context with custom ID, it sets it another ID.
How can I set custom ID value (PK)? 

UPD: When I do insert using context, DbCommand is being generated without ID(PK)

**Comment by Skrimsoft** [comment]
Make the field in the table non-autoincrement and use the attribute:
```csharp
[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
public int ID { get; set; }
```

**Comment by Anamorf** [comment]
Use the attribute:
```csharp
[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
public int ID { get; set; }
```

**Comment by DiscoDancer** [comment]
@Skrimsoft thank you so much. You've just stopped me from parsing and editing raw output of EF.
