### ISSUE TITLE
lost data

### ISSUE THREAD

**Issue by pierluigi-linardi** [msallin/SQLiteCodeFirst#88]
if i have a database with  existing data in table X , then i change model for table X adding property i lost all rows previously created!!! there is a way to avoid this!!!!

**Comment by msallin** [comment]
Hello

You have the option to choose between the following three initializers:
- SqliteCreateDatabaseIfNotExists
- SqliteDropCreateDatabaseAlways
- SqliteDropCreateDatabaseWhenModelChanges

I assume you use SqliteDropCreateDatabaseWhenModelChanges which drops the database if the model changes. I suggest to use SqliteCreateDatabaseIfNotExists. This will only create the DB if it does not exist.
Take into account that you have to apply the migrations to the DB before using the new model.
EF migrations are not supported (https://github.com/msallin/SQLiteCodeFirst/issues/4).

Greetings

**Comment by pierluigi-linardi** [comment]
Ok thanks!!!!
