### ISSUE TITLE
Handle Linux path (Mono)

### ISSUE THREAD

**Issue by mwkldeveloper** [msallin/SQLiteCodeFirst#89]
Hi
I am using it with Mono on Debian.
Everything work fine as i test.
But when i use `|DataDirectory|` in connection string.

it always state that db not exists and create a new one.

and i found that in function ExpandDataDirectory(string path) 
the path string returned contain "\\", not "/",  so it cannot find the existing db.

Now my solution is replace "\\" to "/" before return the path in  ExpandDataDirectory(string path) 
`return fullPath.Replace("\\","/");`

Are there any other solutions for this case on Linux env??

**Comment by msallin** [comment]
I replaced '\\' with Path.DirectorySeparatorChar. 
It would be great if you can test this.
You can download a DLL or the NuGet Package here: https://ci.appveyor.com/project/msallin/sqlitecodefirst/build/artifacts

After a successful test I'll release a new version.

Greetings

**Comment by mwkldeveloper** [comment]
Thanks @msallin 
Tested. It works great with Mono and Window.

**Comment by msallin** [comment]
https://github.com/msallin/SQLiteCodeFirst/releases/tag/v1.3.1.18
https://www.nuget.org/packages/SQLite.CodeFirst/1.3.1.18
