### ISSUE TITLE
Demo Project Doesn't Run

### ISSUE THREAD

**Issue by lansdon** [msallin/SQLiteCodeFirst#9]
I downloaded your master branch and tried to run the console demo. Just wanted to note I had to make a few changes to make it run. 

1) I had to remove the sqlite nuget packages and re-add them (not sure why ?) It was crashing otherwise during DbContext constructor.

2) In the App.config I had to modify my <system.data> section to contain both Sqlite.EF6 and SQLite references like so:

```
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite.EF6" />
      <remove invariant="System.Data.SQLite" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" />
    </DbProviderFactories>
  </system.data>
```

Without this modification it was crashing during the console demo when displaying db contents. The above modification is documented on the SQLite site.

**Comment by lansdon** [comment]
<system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite.EF6" />
      <remove invariant="System.Data.SQLite" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider" invariant="System.Data.SQLite" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" />
    </DbProviderFactories>
  </system.data>

**Comment by code1line** [comment]
Yes, this is a well known issue. 
You also must always be careful when updating the nuget-package. Sometimes the App.config is ruined.

**Comment by msallin** [comment]
Hi lansdon

1) You may could reproduce it and send the error message?
2) As Michael said, thats because you re-added the NuGet packages. The SQLite package has overwritten the App.config. As you will see [here](https://system.data.sqlite.org/index.html/info/2be4298631) the App.config, generated from the NuGet package will _may_ not work.
