### ISSUE TITLE
How set password for sqlite database?

### ISSUE THREAD

**Issue by Rgl88** [msallin/SQLiteCodeFirst#98]
hello
how set password for sqlite database without put password in  connection string in app.config?
i try two following method but not work.
i use below code OnModelCreating and DbContext constructor.

```
            var connnection = this.Database.Connection as SQLiteConnection;
//method 1: (not work)
              var conStr = connnection.ConnectionString + " Password=123;";
             connnection = new SQLiteConnection(conStr);
//method 2: (not work)
            connnection.SetPassword("123");
```

**Comment by msallin** [comment]
This is not releated to Code First but to SQLite.
But as a hint, its easy to look up the password also if you put it into the assembly.

**Comment by Rgl88** [comment]
i obfuscate exe file , but db not have very important data , i want only some nosy programmers can not access db schema easily!
