### ISSUE TITLE
Storing tree structured data with SQLite

### ISSUE THREAD

**Issue by Dirkster99** [msallin/SQLiteCodeFirst#99]
Hi Marc,

I am trying to use SQLiteCodeFirst to store tree structured data
- is that possible with SQLiteCodeFirst?

If not do you know if its possble with EF + SQLite or just with SQLite?

All I can find on this is this blog (see below) but I don't know if thats applicable to .net at all?
http://charlesleifer.com/blog/querying-tree-structures-in-sqlite-using-python-and-the-transitive-closure-extension/

Did you ever come across this problem and may have a sample solution to share?
Thanks Dirk

**Comment by CADbloke** [comment]
You might be better off with a https://en.wikipedia.org/wiki/Graph_database like Neo4j

**Comment by msallin** [comment]
Hi

I think this is not the right place for your question.
This library is to support Code First for SQLite and Entity Framework.
Feel free to reopen the issue if you encounter any problems to create a SQLite-Database out of your EF-Model used to store a tree.

Greetings Marc

**Comment by Dirkster99** [comment]
I have (in the meantime) developed a working version with the Adjecency List Model:
http://mikehillyer.com/articles/managing-hierarchical-data-in-mysql/

Would you be willing to help me turning this version into a CodeFirst version?

I can imagine that it would also help a lot of others out there who want to store
treeview based data in SQLite ...

Thanks Dirk

PS: I don't think I can re-open this :-(
